export default {
  FUNDS_UPDATE: 'FUNDS_UPDATE',

  STOCK_SEARCH_INIT: 'STOCK_SEARCH_INIT',
  STOCK_SEARCH_SUCCESS: 'STOCK_SEARCH_SUCCESS',
  STOCK_SEARCH_ERROR: 'STOCK_SEARCH_ERROR',
  
  STOCK_SEARCH_UPDATE_INIT: 'STOCK_SEARCH_UPDATE_INIT',
  STOCK_SEARCH_UPDATE_SUCCESS: 'STOCK_SEARCH_UPDATE_SUCCESS',
  STOCK_SEARCH_UPDATE_ERROR: 'STOCK_SEARCH_UPDATE_ERROR',

  STOCK_PORTFOLIO_UPDATE_INIT: 'STOCK_PORTFOLIO_UPDATE_INIT',
  STOCK_PORTFOLIO_UPDATE_SUCCESS: 'STOCK_PORTFOLIO_UPDATE_SUCCESS',
  STOCK_PORTFOLIO_UPDATE_ERROR: 'STOCK_PORTFOLIO_UPDATE_ERROR',

  STOCK_BUY_INIT: 'STOCK_BUY_INIT',
  STOCK_BUY_SUCCESS: 'STOCK_BUY_SUCCESS',
  STOCK_BUY_ERROR: 'STOCK_BUY_ERROR',

  STOCK_SELL_INIT: 'STOCK_SELL_INIT',
  STOCK_SELL_SUCCESS: 'STOCK_SELL_SUCCESS',
  STOCK_SELL_ERROR: 'STOCK_SELL_ERROR',
  
  
  MARKET_RESET_INIT: 'MARKET_RESET_INIT',
  MARKET_RESET_SUCCESS: 'MARKET_RESET_SUCCESS',
  MARKET_RESET_ERROR: 'MARKET_RESET_ERROR',
};