export default {
  FUNDS_UPDATE: 'FUNDS_UPDATE',

  STOCK_SEARCH_CHANGE: 'STOCK_SEARCH_CHANGE',
  STOCK_SEARCH_INIT: 'STOCK_SEARCH_INIT',
  STOCK_SEARCH_SUCCESS: 'STOCK_SEARCH_SUCCESS',
  STOCK_SEARCH_ERROR: 'STOCK_SEARCH_ERROR',
  STOCK_SEARCH_CLEAR_ERROR: 'STOCK_SEARCH_CLEAR_ERROR',
  
  SEARCH_POPUP_SHOW: 'SEARCH_POPUP_SHOW',
  SEARCH_POPUP_HIDE: 'SEARCH_POPUP_HIDE',

  STOCK_PORTFOLIO_INIT: 'STOCK_PORTFOLIO_INIT',
  STOCK_PORTFOLIO_SUCCESS: 'STOCK_PORTFOLIO_SUCCESS',
  STOCK_PORTFOLIO_ERROR: 'STOCK_PORTFOLIO_ERROR',
  STOCK_PORTFOLIO_CLEAR_ERROR: 'STOCK_PORTFOLIO_CLEAR_ERROR',

  STOCK_BUY_INIT: 'STOCK_BUY_INIT',
  STOCK_BUY_SUCCESS: 'STOCK_BUY_SUCCESS',
  STOCK_BUY_ERROR: 'STOCK_BUY_ERROR',
  STOCK_BUY_CLEAR_ERROR: 'STOCK_BUY_CLEAR_ERROR',

  STOCK_SELL_INIT: 'STOCK_SELL_INIT',
  STOCK_SELL_SUCCESS: 'STOCK_SELL_SUCCESS',
  STOCK_SELL_ERROR: 'STOCK_SELL_ERROR',
  STOCK_SELL_CLEAR_ERROR: 'STOCK_SELL_CLEAR_ERROR',
  
  STOCK_POPUP_SHOW: 'STOCK_POPUP_SHOW',
  STOCK_POPUP_HIDE: 'STOCK_POPUP_HIDE',
  STOCK_POPUP_UPDATE: 'STOCK_POPUP_UPDATE',
  STOCK_POPUP_ERROR: 'STOCK_POPUP_ERROR',
  STOCK_POPUP_CLEAR_ERROR: 'STOCK_POPUP_CLEAR_ERROR',
  
  MARKET_UPDATE_INIT: 'MARKET_UPDATE_INIT',
  MARKET_UPDATE_SUCCESS: 'MARKET_UPDATE_SUCCESS',
  MARKET_PORTFOLIO_UPDATE_SUCCESS: 'MARKET_PORTFOLIO_UPDATE_SUCCESS',
  MARKET_SEARCH_UPDATE_SUCCESS: 'MARKET_SEARCH_UPDATE_SUCCESS',
  MARKET_UPDATE_ERROR: 'MARKET_UPDATE_ERROR',
  MARKET_UPDATE_CLEAR_ERROR: 'MARKET_UPDATE_CLEAR_ERROR',
  
  MARKET_RESET_INIT: 'MARKET_RESET_INIT',
  MARKET_RESET_SUCCESS: 'MARKET_RESET_SUCCESS',
  MARKET_RESET_ERROR: 'MARKET_RESET_ERROR',
  MARKET_RESET_CLEAR_ERROR: 'MARKET_RESET_CLEAR_ERROR',

  PORTFOLIO_SORT_CHANGE: 'PORTFOLIO_SORT_CHANGE',
};